# CMake generated Testfile for 
# Source directory: /home/dysta/Cours/L3/prog-sys/projet
# Build directory: /home/dysta/Cours/L3/prog-sys/projet
# 
# This file includes the relevant testing commands required for 
# testing this directory and lists subdirectories to be tested as well.
add_test(test.success "sample" "-t" "2" "-r" "test.success" "-x")
set_tests_properties(test.success PROPERTIES  PASS_REGULAR_EXPRESSION "SUCCESS" TIMEOUT "4")
add_test(test.failure "sample" "-t" "2" "-r" "test.failure" "-x")
set_tests_properties(test.failure PROPERTIES  PASS_REGULAR_EXPRESSION "FAILURE" TIMEOUT "4")
add_test(test.segfault "sample" "-t" "2" "-r" "test.segfault" "-x")
set_tests_properties(test.segfault PROPERTIES  PASS_REGULAR_EXPRESSION "KILLED" TIMEOUT "4")
add_test(test.assert "sample" "-t" "2" "-r" "test.assert" "-x")
set_tests_properties(test.assert PROPERTIES  PASS_REGULAR_EXPRESSION "KILLED" TIMEOUT "4")
add_test(test.sleep "sample" "-t" "2" "-r" "test.sleep" "-x")
set_tests_properties(test.sleep PROPERTIES  PASS_REGULAR_EXPRESSION "TIMEOUT" TIMEOUT "4")
add_test(test.alarm "sample" "-t" "2" "-r" "test.alarm" "-x")
set_tests_properties(test.alarm PROPERTIES  PASS_REGULAR_EXPRESSION "KILLED" TIMEOUT "4")
add_test(test.args "sample" "-t" "2" "-r" "test.args" "-x")
set_tests_properties(test.args PROPERTIES  PASS_REGULAR_EXPRESSION "SUCCESS" TIMEOUT "4")
add_test(test.infiniteloop "sample" "-t" "2" "-r" "test.infiniteloop" "-x")
set_tests_properties(test.infiniteloop PROPERTIES  PASS_REGULAR_EXPRESSION "TIMEOUT" TIMEOUT "4")
add_test(sample_list_test "bash" "-c" "/home/dysta/Cours/L3/prog-sys/projet/sample -R test -l | wc -l")
set_tests_properties(sample_list_test PROPERTIES  PASS_REGULAR_EXPRESSION "10" TIMEOUT "1")
add_test(sample_list_othertest "bash" "-c" "/home/dysta/Cours/L3/prog-sys/projet/sample -R othertest -l | wc -l")
set_tests_properties(sample_list_othertest PROPERTIES  PASS_REGULAR_EXPRESSION "2" TIMEOUT "1")
add_test(sample_list_onetest "sample" "-r" "test.hello" "-l")
set_tests_properties(sample_list_onetest PROPERTIES  PASS_REGULAR_EXPRESSION "test.hello" TIMEOUT "1")
add_test(sample_run_all "bash" "-c" "/home/dysta/Cours/L3/prog-sys/projet/sample -R test -t 2 -x -c &> /dev/null ; echo \"NFAILURES=$?\"")
set_tests_properties(sample_run_all PROPERTIES  PASS_REGULAR_EXPRESSION "NFAILURES=6" TIMEOUT "30")
add_test(sample_main "sample_main")
set_tests_properties(sample_main PROPERTIES  TIMEOUT "5")
add_test(hello "hello" "-c" "-x")
add_test(hello_grep_success "hello" "-x" "-g" "hello")
set_tests_properties(hello_grep_success PROPERTIES  PASS_REGULAR_EXPRESSION "SUCCESS" TIMEOUT "4")
add_test(hello_grep_failure "hello" "-x" "-g" "helo")
set_tests_properties(hello_grep_failure PROPERTIES  PASS_REGULAR_EXPRESSION "FAILURE" TIMEOUT "4")
add_test(hello_diff_success "hello" "-x" "-d" "hello.expected")
set_tests_properties(hello_diff_success PROPERTIES  PASS_REGULAR_EXPRESSION "SUCCESS" TIMEOUT "4")
add_test(hello_diff_failure "hello" "-x" "-d" "hello.notexpected")
set_tests_properties(hello_diff_failure PROPERTIES  PASS_REGULAR_EXPRESSION "FAILURE" TIMEOUT "4")
